/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.TablaInventario;

/**
 *
 * @author shari
 */
public class Inventario extends javax.swing.JFrame {
    public TablaInventario modelo = new TablaInventario();
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        iniciarTabla();
    }
    
    public void iniciarTabla(){
        modelo.inicializar(TablaInventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        MenuBarInventario = new javax.swing.JMenuBar();
        MenuInventario = new javax.swing.JMenu();
        MenuItemActualizar = new javax.swing.JMenuItem();
        MenuItemActualizarVentana = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        MenuItemCrear = new javax.swing.JMenuItem();
        MenuItemEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(TablaInventario);

        MenuInventario.setText("Inventario");

        MenuItemActualizar.setText("Actualizar cantidad de producto");
        MenuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarActionPerformed(evt);
            }
        });
        MenuInventario.add(MenuItemActualizar);

        MenuItemActualizarVentana.setText("Actualizar ventana");
        MenuItemActualizarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarVentanaActionPerformed(evt);
            }
        });
        MenuInventario.add(MenuItemActualizarVentana);

        MenuBarInventario.add(MenuInventario);

        MenuProductos.setText("Productos");

        MenuItemCrear.setText("Crear nuevo producto");
        MenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCrearActionPerformed(evt);
            }
        });
        MenuProductos.add(MenuItemCrear);

        MenuItemEliminar.setText("Eliminar producto");
        MenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarActionPerformed(evt);
            }
        });
        MenuProductos.add(MenuItemEliminar);

        MenuBarInventario.add(MenuProductos);

        setJMenuBar(MenuBarInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarActionPerformed
        // TODO add your handling code here:
        new ActualizarCantidad().setVisible(true);
    }//GEN-LAST:event_MenuItemActualizarActionPerformed

    private void MenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCrearActionPerformed
        // TODO add your handling code here:
        new CrearProducto().setVisible(true);
    }//GEN-LAST:event_MenuItemCrearActionPerformed

    private void MenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarActionPerformed
        // TODO add your handling code here:
        new EliminarProducto().setVisible(true);
    }//GEN-LAST:event_MenuItemEliminarActionPerformed

    private void MenuItemActualizarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarVentanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inventario().setVisible(true);
    }//GEN-LAST:event_MenuItemActualizarVentanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarInventario;
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JMenuItem MenuItemActualizar;
    private javax.swing.JMenuItem MenuItemActualizarVentana;
    private javax.swing.JMenuItem MenuItemCrear;
    private javax.swing.JMenuItem MenuItemEliminar;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
